void cil_add_file(){}
void cil_build_policydb(){}
void cil_compile(){}
void cil_db_destroy(){}
void cil_db_init(){}
void cil_filecons_to_string(){}
void cil_selinuxusers_to_string(){}
void cil_set_attrs_expand_generated(){}
void cil_set_attrs_expand_size(){}
void cil_set_disable_dontaudit(){}
void cil_set_disable_neverallow(){}
void cil_set_handle_unknown(){}
void cil_set_log_handler(){}
void cil_set_log_level(){}
void cil_set_mls(){}
void cil_set_multiple_decls(){}
void cil_set_policy_version(){}
void cil_set_preserve_tunables(){}
void cil_set_qualified_names(){}
void cil_set_target_platform(){}
void cil_userprefixes_to_string(){}
void cil_write_build_ast(){}
void cil_write_parse_ast(){}
void cil_write_policy_conf(){}
void cil_write_resolve_ast(){}
